import os

aws_server = ".lambda-url.us-west-2.on.aws/"

# Determine the stage by checking the CHALICE_STAGE environment variable
stage = os.getenv('CHALICE_STAGE', 'local')

service_uris = {
    'prod': {
        'analyze': "https://2av3vd7bxvxu3zfymtdgqziuoy0lvpge" + aws_server,
        'codeguidelines': "https://ssmhqxozg6ixnk5abyhnezf5ya0seyby" + aws_server,
        'user_organizations': "https://ptb5spl6kvsuioc5zkrgyncrve0jyrew" + aws_server,
        'compliance': "https://7vtdrtujboyw4ft7af7j2aimqi0wzwzd" + aws_server,
        'blueprint': "https://hb34ftyxhjnd7jvxbmlsmddct40hvrni" + aws_server,
        'flowdiagram': "https://b3pflzry5l5wbaenwtdytiv7se0ykzkc" + aws_server,
        'customer_portal': "https://roxbi254sch3yijt7tqbz4s7jq0jxddr" + aws_server,
        'compliance_function': "https://srsybz6dbjz45skdwq6quou4ua0rxbnk" + aws_server,
        'customprocess': "https://7ntcvdqj4r23uklomzmeiwq7nq0dhblq" + aws_server,
        'analyze_function': "https://scqfjxbrko57bekv4lqkvu24fa0cmapi" + aws_server,
        'summarize': "https://tu5zdmjxvvzbzih6yytjtbm6fa0uvjba" + aws_server,
        'explain': "https://vdcg2nzj2jtzmtzzcmfwbvg4ey0jxghj" + aws_server,
        'testgen': "https://mqxkx5m7hehbskfvrcfwctbt7y0gghab" + aws_server,
        'generate': "https://egw2c7dn5vz3leffr3mfqodx3a0perwp" + aws_server,
        'performance': "https://zr4gcodfteyi3zi5skcqnx2fge0rnjdk" + aws_server,
        'performance_function': "https://vhdpiji3mrr5ass7o5tx5mx5oa0nrjth" + aws_server,
        'compare_code': "https://h4vna4mvnun3jkfmoceobnnaau0drouk" + aws_server,
        'quick-blueprint': "https://vryv4jotc6rghitxmwaz5whrqm0obehc" + aws_server,
        'draft-blueprint': "https://7qpij3jplvcmdaojfumgj32e7e0vcchc" + aws_server,
        'quick-summary': "https://ur4c2bfxchy626dzumtengt4ta0bpser" + aws_server,
    },
    'dev': {
        'analyze': "https://iyn66vkb6lmlcb4log6d3ah7d40axgqu" + aws_server,
        'codeguidelines': "https://4govp5ze7uyio3kjehtarpv24u0nabhw" + aws_server,
        'user_organizations': "https://cro3oyez4g56b33hvglfwytg3q0alxrz" + aws_server,
        'compliance': "https://q57gtrfpkuzquelgqtnncpjwta0nngfx" + aws_server,
        'blueprint': "https://67wxr6xq76bj5jiaoct5qjzble0wfmdt" + aws_server,
        'flowdiagram': "https://54t2jblqus2ou7letg3g2eph7y0aydtk" + aws_server,
        'customer_portal': "https://hry4lqp3ktulatehaowyzhkbja0mkjob" + aws_server,
        'compliance_function': "https://t4so4gqwf5rr5fr7pvlpytvkne0prvcv" + aws_server,
        'customprocess': "https://fudpixnolc7qohinghnum2nlm40wmozy" + aws_server,
        'analyze_function': "https://fubldwjkv4nau5qcnbrqilv6ba0dmkcc" + aws_server,
        'summarize': "https://sh6w6cyjee6wmtmlqutbxy6d2y0vaaas" + aws_server,
        'explain': "https://jorsb57zbzwcxcjzl2xwvah45i0mjuxs" + aws_server,
        'testgen': "https://gylbelpkobvont6vpxp4ihw5fm0iwnto" + aws_server,
        'generate': "https://ukkqda6zl22nd752blcqlv3rum0ziwnq" + aws_server,
        'performance': "https://kh5r75yzyxe3idb223bei7tzni0vdyab" + aws_server,
        'performance_function': "https://6ucgf5nhzygxehglg5r7nd73640lykwa" + aws_server,
        'compare_code': "https://ztnhbmjlticv336bbmwlxsuphy0ctclu" + aws_server,
        'quick-blueprint': "https://c2m6d7mgrgypx3mzktbxoawfpa0acsja" + aws_server,
        'draft-blueprint': "https://b7zk2dm2haygvcluz4jx2by3vm0ypljn" + aws_server,
        'quick-summary': "https://vyuhthnoinejl6hle7cq7frzta0uzjzp" + aws_server,
    },
    'local': {
        'analyze': "http://127.0.0.1:8000/analyze",
        'codeguidelines': "http://127.0.0.1:8000/codeguidelines",
        'user_organizations': "http://127.0.0.1:8000/user_organizations",
        'compliance': "http://127.0.0.1:8000/compliance",
        'blueprint': "http://127.0.0.1:8000/blueprint",
        'flowdiagram': "http://127.0.0.1:8000/flowdiagram",
        'customer_portal': "http://127.0.0.1:8000/customer_portal",
        'compliance_function': "http://127.0.0.1:8000/compliance_function",
        'customprocess': "http://127.0.0.1:8000/customprocess",
        'analyze_function': "http://127.0.0.1:8000/analyze_function",
        'summarize': "http://127.0.0.1:8000/summarize",
        'explain': "http://127.0.0.1:8000/explain",
        'testgen': "http://127.0.0.1:8000/testgen",
        'generate': "http://127.0.0.1:8000/generate",
        'performance': "http://127.0.0.1:8000/performance",
        'performance_function': "http://127.0.0.1:8000/performance_function",
        'compare_code': "http://127.0.0.1:8000/compare_code",
        'quick-blueprint': "http://127.0.0.1:8000/quick-blueprint",
        'draft-blueprint': "http://127.0.0.1:8000/draft-blueprint",
        'quick-summary': "http://127.0.0.1:8000/quick-summary",
    }
}
